apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-service
    owner: gray
  name: api-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9001
  selector:
    app: api-service
status:
  loadBalancer: {}
